name: Auto Deploy Swarm
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: infinity-x-one-swarm-system
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy infinity-swarm-backend \
            --source . \
            --region us-east1 \
            --platform managed \
            --allow-unauthenticated
