name: Infinity-X Auto-Tag

on:
  push:
    branches: [main]

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Auto-tag new release
        run: |
          TAG="v$(date +%Y%m%d-%H%M)"
          git tag -a $TAG -m "Automated version tag $TAG"
          git push origin $TAG
