name: Infinity-X Auto-Ops

on:
  schedule:
    - cron: "0 2 * * *"
  push:
    branches: [main]

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run Auto-Ops
        run: |
          chmod +x scripts/production_auto_ops.sh
          ./scripts/production_auto_ops.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GOOGLE_PROJECT_ID: infinity-x-one-swarm-system
      - uses: actions/upload-artifact@v4
        with:
          name: auto-ops-logs
          path: logs/
