name: Infinity-X GCP Sync

on:
  schedule:
    - cron: "30 2 * * *"
  push:
    branches: [main]

jobs:
  gcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: infinity-x-one-swarm-system
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Sync Secrets
        run: |
          gcloud secrets versions access latest --secret=OPENAI_API_KEY > secrets/OPENAI_API_KEY.txt
          gcloud secrets versions access latest --secret=GROQ_API_KEY > secrets/GROQ_API_KEY.txt
