name: Launch Infinity Stack

on:
  workflow_dispatch: {}
jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend agents
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r backend/requirements.txt

      - name: Start agents (background)
        run: |
          nohup python backend/agents/infinity_agent/main.py &
          nohup python backend/agents/codex_agent/main.py &
          nohup python backend/agents/strategist_agent/main.py &
