name: Infinity-X Schema & Memory Sync
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: infinity-x-one-swarm-system
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          export_default_credentials: true

      - name: Schema Sync
        run: bash scripts/schema_sync.sh

      - name: Memory Sync
        run: bash scripts/memory_sync.sh

      - name: Commit & Push Updates
        run: |
          git config user.name "Infinity-X Bot"
          git config user.email "bot@infinityx.local"
          git add docs/SCHEMA_STATUS.md || true
          git commit -m "🧠 Automated Schema & Memory Sync" || true
          git push || true
