name: Infinity-X System Auto-Heal

on:
  workflow_run:
    workflows: ["Infinity-X Auto-Ops", "Infinity-X Vercel Deploy", "Infinity-X GCP Sync"]
    types: [completed]

jobs:
  heal_and_fix:
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run repo auto-heal
        run: |
          chmod +x scripts/repo_autoheal.sh
          ./scripts/repo_autoheal.sh

      - name: Run code auto-fix
        run: |
          python3 scripts/code_autofix.py

      - name: Run cloud auto-heal
        run: |
          chmod +x scripts/cloud_autoheal.sh
          ./scripts/cloud_autoheal.sh
        env:
          GOOGLE_PROJECT_ID: infinity-x-one-swarm-system
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      - name: Commit heal logs
        run: |
          git add .
          git commit -m "🩺 System Auto-Heal $(date)" || true
          git push origin main || true
